#define selectorOffset 40
static xpm_row_t selector[] = {

    "13 12 2 1 ",
    "  c None",
    ". c #B8032C",
    /* pixels */
    "     ...     ",
    "    .....    ",
    "   ... ...   ",
    "   ..   ..   ",
    "   ..   ..   ",
    "   ... ...   ",
    "    .....    ",
    "    .....    ",
    "     ...     ",
    "     ...     ",
    "      .      ",
    "      .      "};
static xpm_row_t arwing[] = {
    "16 14 9 1 ",
    "  c None",
    ". c #202020",
    "X c #209020",
    "o c #585890",
    "O c #3050D8",
    "+ c #4098F8",
    "@ c #9090C8",
    "# c #C8C8F8",
    "$ c #F8F8F8",
    "                ",
    "                ",
    "                ",
    "       ..       ",
    "      .##.      ",
    "      .$$.      ",
    "     .+$$+.     ",
    "    ..+..+..    ",
    "   .@$.XX.$@.   ",
    "  .@$......$@.  ",
    "  .#.      .#.  ",
    "  ..        ..  ",
    "                ",
    "                ",
    "                "};
static xpm_row_t moon[] = {

    "64 64 4 1 ",
    "  c none",
    ". c #444444",
    "X c #636363",
    "o c #8b8b8b",
    /* pixels */
    "                                                                ",
    "                                                                ",
    "                          XXXXXXXXXXXX                          ",
    "                          XXXXXXXXXXXX                          ",
    "                    XXXXXXooooooooooooXXXXXX                    ",
    "                    XXXXXXooooooooooooXXXXXX                    ",
    "                XXXXXXoooooooooo......ooooooXXXX                ",
    "                XXXXXXoooooooooo......ooooooXXXX                ",
    "              XXXXooooooooooooXXXXXX..oo......ooXX              ",
    "              XXXXooooooooooooXXXXXX..oo......ooXX              ",
    "            XXXXoooooo........ooooooooXXXXXXXX..ooXX            ",
    "            XXXXoooooo........ooooooooXXXXXXXX..ooXX            ",
    "          XXXXXXoooo..XXXXXXXX....ooooooooXXXXXX..ooXX          ",
    "          XXXXXXoooo..XXXXXXXX....ooooooooXXXXXX..ooXX          ",
    "        XXXXXXoooo..XXXXXXXXXXXXXX....ooooooooXXXX..ooXX        ",
    "        XXXXXXoooo..XXXXXXXXXXXXXX....ooooooooXXXX..ooXX        ",
    "        XXXXXXooooXXXXXXXXooooooXXXX..oooo....ooooXXooXX        ",
    "        XXXXXXooooXXXXXXXXooooooXXXX..oooo....ooooXXooXX        ",
    "      XXXX..XXooooXXXXoooooooooooooooooo..XXXX..ooooooooXX      ",
    "      XXXX..XXooooXXXXoooooooooooooooooo..XXXX..ooooooooXX      ",
    "      XX....XXoooooooooooooooooooooooo..XXXXXXooooooooooXX      ",
    "      XX....XXoooooooooooooooooooooooo..XXXXXXooooooooooXX      ",
    "      XXXXXXXXoooooooo........ooooooooXXXXXXoooooo....ooXX      ",
    "      XXXXXXXXoooooooo........ooooooooXXXXXXoooooo....ooXX      ",
    "    XXXXXXXXXXooooooooXXXXXX..ooooooooooooooooooooXXXXooXXXX    ",
    "    XXXXXXXXXXooooooooXXXXXX..ooooooooooooooooooooXXXXooXXXX    ",
    "    XX....XXXXXXooooooXXXXXXoooo..oooooo....ooooooXXooooXXXX    ",
    "    XX....XXXXXXooooooXXXXXXoooo..oooooo....ooooooXXooooXXXX    ",
    "    XX....XXXXXXooooooooXXXXooooXX..ooXXXXXX....ooooooooXXXX    ",
    "    XX....XXXXXXooooooooXXXXooooXX..ooXXXXXX....ooooooooXXXX    ",
    "    XX..XXXXXXXXXXooooooooooooooXXXXooooXXXXXX..ooooooXXXXXX    ",
    "    XX..XXXXXXXXXXooooooooooooooXXXXooooXXXXXX..ooooooXXXXXX    ",
    "    XXXXXX..XXXXXXXXooooooooooooooooooooooXXXX..ooooooXXXXXX    ",
    "    XXXXXX..XXXXXXXXooooooooooooooooooooooXXXX..ooooooXXXXXX    ",
    "    XXXXXX......XXXXXXooooooooooooooXXooooooXXooooooXXXXXXXX    ",
    "    XXXXXX......XXXXXXooooooooooooooXXooooooXXooooooXXXXXXXX    ",
    "      XXXX......XXXXXXXXXXooooooooooooooooooooooXXXXXX..XX      ",
    "      XXXX......XXXXXXXXXXooooooooooooooooooooooXXXXXX..XX      ",
    "      XXXXXX..XXXX..XXXXXXXXXXooooooooooooooXXXXXXXXXXXXXX      ",
    "      XXXXXX..XXXX..XXXXXXXXXXooooooooooooooXXXXXXXXXXXXXX      ",
    "      XXXXXXXXXX......XXXXXXXXXXXXXXXXXXXXXXXXXXXX..XXXXXX      ",
    "      XXXXXXXXXX......XXXXXXXXXXXXXXXXXXXXXXXXXXXX..XXXXXX      ",
    "        XXXXXXXXXX....XXXX..............XXXXXXXXXXXXXXXX        ",
    "        XXXXXXXXXX....XXXX..............XXXXXXXXXXXXXXXX        ",
    "        XX......XXXXXXXXXX............XXXXXXXX....XXXXXX        ",
    "        XX......XXXXXXXXXX............XXXXXXXX....XXXXXX        ",
    "          XX......XXXXXXXXXX......XXXXXXXX........XXXX          ",
    "          XX......XXXXXXXXXX......XXXXXXXX........XXXX          ",
    "            XX....XXXXXX..XXXXXXXXXXXX..........XXXX            ",
    "            XX....XXXXXX..XXXXXXXXXXXX..........XXXX            ",
    "              XXXXXX..XXXX..XXXXXXXX........XXXXXX              ",
    "              XXXXXX..XXXX..XXXXXXXX........XXXXXX              ",
    "                XXXXXXXX....XX....XXXXXXXXXXXXXX                ",
    "                XXXXXXXX....XX....XXXXXXXXXXXXXX                ",
    "                    XXXXXXXXXX......XXXXXXXX                    ",
    "                    XXXXXXXXXX......XXXXXXXX                    ",
    "                          XXXXXXXXXXXX                          ",
    "                          XXXXXXXXXXXX                          ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                                "};

static xpm_row_t green[] = {
    /* columns rows colors chars-per-pixel */
    "64 64 4 1 ",
    "  c none",
    ". c #286A49",
    "X c #399969",
    "o c #5FC592",
    /* pixels */
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                          XXXXXXXXXXXX                          ",
    "                          XXXXXXXXXXXX                          ",
    "                    XXXXXXXXooooooooooXXXXXX                    ",
    "                    XXXXXXXXooooooooooXXXXXX                    ",
    "                XXXXXXXXooooooooooooXXXXXXXXXXXX                ",
    "                XXXXXXXXooooooooooooXXXXXXXXXXXX                ",
    "              XXXXXXXXooooooooooXXXXXXXXXXXXooooXX              ",
    "              XXXXXXXXooooooooooXXXXXXXXXXXXooooXX              ",
    "            XXXXXXXXooooooooXXXXXXXXXXooooooooooXXXX            ",
    "            XXXXXXXXooooooooXXXXXXXXXXooooooooooXXXX            ",
    "          XXXXXXXXooooooooXXXXXXXXXXooooooooooXXXXoooo          ",
    "          XXXXXXXXooooooooXXXXXXXXXXooooooooooXXXXoooo          ",
    "        XXXXXXXXXXooooXXXXXXXXXXooooooooooXXXXXXooooooXX        ",
    "        XXXXXXXXXXooooXXXXXXXXXXooooooooooXXXXXXooooooXX        ",
    "        XXXXXXXXooooXXXXXXXXXXooooooooXXXXXXooooooooXXXX        ",
    "        XXXXXXXXooooXXXXXXXXXXooooooooXXXXXXooooooooXXXX        ",
    "      XXXXXXXXXXooXXXXXXXXXXooooooooXXXXooooooooooXXXXXXXX      ",
    "      XXXXXXXXXXooXXXXXXXXXXooooooooXXXXooooooooooXXXXXXXX      ",
    "      XXXXXXXXXXXXXXXXXXXXooooooooXXXXooooooooooXXXXXXXXXX      ",
    "      XXXXXXXXXXXXXXXXXXXXooooooooXXXXooooooooooXXXXXXXXXX      ",
    "      XXXXXXXXXXXXXXXXXXooooooooXXXXooooooooooXXXXXXXXooXX      ",
    "      XXXXXXXXXXXXXXXXXXooooooooXXXXooooooooooXXXXXXXXooXX      ",
    "    XXXXXXXX....XXXXXXooooooooXXXXooooooooooXXXXXXXXooooooXX    ",
    "    XXXXXXXX....XXXXXXooooooooXXXXooooooooooXXXXXXXXooooooXX    ",
    "    XXXXXX......XXXXooooooooXXXXooooooooooXXXXXXXXooooooooXX    ",
    "    XXXXXX......XXXXooooooooXXXXooooooooooXXXXXXXXooooooooXX    ",
    "    XXXX..........ooooooooXXXXooooooooXXXXXXXXXXooooooooooXX    ",
    "    XXXX..........ooooooooXXXXooooooooXXXXXXXXXXooooooooooXX    ",
    "    ............XXooooooXXXXooooooooXXXXXXXXXXoooooooooooo..    ",
    "    ............XXooooooXXXXooooooooXXXXXXXXXXoooooooooooo..    ",
    "    ........XXXXXXXXooXXXXooooooooXXXXXXXXXXoooooooooooo....    ",
    "    ........XXXXXXXXooXXXXooooooooXXXXXXXXXXoooooooooooo....    ",
    "    ......XXXXXXXXXXXXXXooooooooXXXXXXXXXXoooooooooooooo....    ",
    "    ......XXXXXXXXXXXXXXooooooooXXXXXXXXXXoooooooooooooo....    ",
    "      ..XXXXXXXXXXXX..XXooooooXXXXXXXXXXoooooooooooooo....      ",
    "      ..XXXXXXXXXXXX..XXooooooXXXXXXXXXXoooooooooooooo....      ",
    "      XXXXXXXXXXXX....XXooooXXXXXXXXXXoooooooooooooo......      ",
    "      XXXXXXXXXXXX....XXooooXXXXXXXXXXoooooooooooooo......      ",
    "      XXXXXXXXXX....XXXXXXXXXXXXXXXXXXooooooooooXX......XX      ",
    "      XXXXXXXXXX....XXXXXXXXXXXXXXXXXXooooooooooXX......XX      ",
    "        XXXXXX....XXXXXXXX......XXXXooooooooXX........XX        ",
    "        XXXXXX....XXXXXXXX......XXXXooooooooXX........XX        ",
    "        XXXX....XXXXXXXX........XXXXXXXXXXXX........XXXX        ",
    "        XXXX....XXXXXXXX........XXXXXXXXXXXX........XXXX        ",
    "          ....XXXXXXXX..........XXXXXXXXXX........XXXX          ",
    "          ....XXXXXXXX..........XXXXXXXXXX........XXXX          ",
    "            XXXXXXXX..........XXXXXXXXXX........XXXX            ",
    "            XXXXXXXX..........XXXXXXXXXX........XXXX            ",
    "              XX..........XXXXXXXXXXXX......XXXXXX              ",
    "              XX..........XXXXXXXXXXXX......XXXXXX              ",
    "                ........XXXXXXXXXX........XXXXXX                ",
    "                ........XXXXXXXXXX........XXXXXX                ",
    "                    XXXXXXXXXXXX........XXXX                    ",
    "                    XXXXXXXXXXXX........XXXX                    ",
    "                          XXXX........                          ",
    "                          XXXX........                          ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                                "};

static xpm_row_t mars[] = {
    /* columns rows colors chars-per-pixel */
    "64 64 3 1 ",
    "  c none",
    ". c #BD3E07",
    "X c #E5571F",
    /* pixels */
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                          ............                          ",
    "                          ............                          ",
    "                    ......XXXXXXXXXXXX......                    ",
    "                    ......XXXXXXXXXXXX......                    ",
    "                ......XXXXXX..XX......XXXXXX....                ",
    "                ......XXXXXX..XX......XXXXXX....                ",
    "              ....XXXXXX..XXXX........XX....XXXX..              ",
    "              ....XXXXXX..XXXX........XX....XXXX..              ",
    "            ....XX..XX..XX..XXXXXXXXXX....XXXXXXXX..            ",
    "            ....XX..XX..XX..XXXXXXXXXX....XXXXXXXX..            ",
    "          ....XX..XX..XX......XXXXXXXXXXXX....XX..XX..          ",
    "          ....XX..XX..XX......XXXXXXXXXXXX....XX..XX..          ",
    "        ......XXXX....XXXXXXXXXXXX....XX........XXXXXX..        ",
    "        ......XXXX....XXXXXXXXXXXX....XX........XXXXXX..        ",
    "        ....XXXX..XX....XXXX..XX........XXXX........XX..        ",
    "        ....XXXX..XX....XXXX..XX........XXXX........XX..        ",
    "      ......XX....XX....XX....XXXX....XXXXXXXXXX......XX..      ",
    "      ......XX....XX....XX....XXXX....XXXXXXXXXX......XX..      ",
    "      ....XX..XX....XXXX..XX..XX..XX....XX..XXXXXXXX..XX..      ",
    "      ....XX..XX....XXXX..XX..XX..XX....XX..XXXXXXXX..XX..      ",
    "      ....XXXX........XX..XXXXXXXX........XX..XX..XXXXXX..      ",
    "      ....XXXX........XX..XXXXXXXX........XX..XX..XXXXXX..      ",
    "    ......XX....XX..XX..XXXXXXXX..XX....XXXXXX..XXXX..XX....    ",
    "    ......XX....XX..XX..XXXXXXXX..XX....XXXXXX..XXXX..XX....    ",
    "    ..............XXXX....XXXX..XXXXXX..XXXX....XX..........    ",
    "    ..............XXXX....XXXX..XXXXXX..XXXX....XX..........    ",
    "    ....XX....XX....XX......XX..XX....XXXX..XX..XXXX..XX....    ",
    "    ....XX....XX....XX......XX..XX....XXXX..XX..XXXX..XX....    ",
    "    ............XX......XXXXXXXXXX......XXXXXXXX..XXXXXX....    ",
    "    ............XX......XXXXXXXXXX......XXXXXXXX..XXXXXX....    ",
    "    ....XX..XX......XX..XXXX..XX......XX..XX..XXXX....XX....    ",
    "    ....XX..XX......XX..XXXX..XX......XX..XX..XXXX....XX....    ",
    "    ..........XX......XXXX..XX......XX..XXXXXX..XX..XXXX....    ",
    "    ..........XX......XXXX..XX......XX..XXXXXX..XX..XXXX....    ",
    "      ..........XX..XXXX..XXXXXX....XXXXXX..XXXXXXXXXX....      ",
    "      ..........XX..XXXX..XXXXXX....XXXXXX..XXXXXXXXXX....      ",
    "      ....XX..XX............XXXXXX......XXXX....XX..XX....      ",
    "      ....XX..XX............XXXXXX......XXXX....XX..XX....      ",
    "      ..............XX..XX....XXXXXX......XXXX....XX......      ",
    "      ..............XX..XX....XXXXXX......XXXX....XX......      ",
    "        ....XX........XX....XXXX..XXXXXX..XX....XX......        ",
    "        ....XX........XX....XXXX..XXXXXX..XX....XX......        ",
    "        ........XX........XX....XX..XX..XX..............        ",
    "        ........XX........XX....XX..XX..XX..............        ",
    "          ........XX..XX..............XX....XX..XX....          ",
    "          ........XX..XX..............XX....XX..XX....          ",
    "            ................XX....XXXX..XX..........            ",
    "            ................XX....XXXX..XX..........            ",
    "              ..........XX..................XX....              ",
    "              ..........XX..................XX....              ",
    "                ................XX..XX..........                ",
    "                ................XX..XX..........                ",
    "                    ........................                    ",
    "                    ........................                    ",
    "                          ............                          ",
    "                          ............                          ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                                "};

static xpm_row_t ocean[] = {
    /* columns rows colors chars-per-pixel */
    "64 64 5 1 ",
    "  c none",
    ". c #4839FD",
    "X c #786DFE",
    "o c #838383",
    "O c #E1E1E1",
    /* pixels */
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                          ............                          ",
    "                          ............                          ",
    "                    ........XXXXXXXXXX......                    ",
    "                    ........XXXXXXXXXX......                    ",
    "                ........XXXXXXXXXXXXXXXXXXXX....                ",
    "                ........XXXXXXXXXXXXXXXXXXXX....                ",
    "              ........XXOOOOOOXXXXXXXXXXXXXXXXXX..              ",
    "              ........XXOOOOOOXXXXXXXXXXXXXXXXXX..              ",
    "            ......ooOOOOOOXXXXXXXXXXXXXXXXXXXXXXXX..            ",
    "            ......ooOOOOOOXXXXXXXXXXXXXXXXXXXXXXXX..            ",
    "          ....ooooOOOOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..          ",
    "          ....ooooOOOOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..          ",
    "        ..ooooooooXXXXXXXXXXXXXXXXXXOOOOOOOOOOOOXXXXXX..        ",
    "        ..ooooooooXXXXXXXXXXXXXXXXXXOOOOOOOOOOOOXXXXXX..        ",
    "        oooo....XXXXXXXXXXXXOOOOOOOOOOOOOOOOXXXXXXXXXX..        ",
    "        oooo....XXXXXXXXXXXXOOOOOOOOOOOOOOOOXXXXXXXXXX..        ",
    "      ..........XXXXXXXXOOOOOOOOOOOOXXXXXXXXXXXXXXXXXXXX..      ",
    "      ..........XXXXXXXXOOOOOOOOOOOOXXXXXXXXXXXXXXXXXXXX..      ",
    "      ..........XXXXOOOOOOOOOOXXXXXXXXXXXXXXXXXXOOOOOOOO..      ",
    "      ..........XXXXOOOOOOOOOOXXXXXXXXXXXXXXXXXXOOOOOOOO..      ",
    "      ..........XXXXXXXXXXXXXXXXXXXXXXXXXXXXOOOOOOXXXXXX..      ",
    "      ..........XXXXXXXXXXXXXXXXXXXXXXXXXXXXOOOOOOXXXXXX..      ",
    "    ............XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..    ",
    "    ............XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..    ",
    "    ............XXXXXXOOOOOOOOOOOOXXXXXXXXXXXXXXXXXXXXXXXX..    ",
    "    ............XXXXXXOOOOOOOOOOOOXXXXXXXXXXXXXXXXXXXXXXXX..    ",
    "    ........ooooooOOOOOOOOOOOOXXXXXXXXXXXXXXXXXXXXXXXXXXXX..    ",
    "    ........ooooooOOOOOOOOOOOOXXXXXXXXXXXXXXXXXXXXXXXXXXXX..    ",
    "    ....ooooooooooOOOOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..    ",
    "    ....ooooooooooOOOOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..    ",
    "    ..oooooooo......XXXXXXXXXXXXXXXXXXXXXXXXXXOOOOOOOOOO....    ",
    "    ..oooooooo......XXXXXXXXXXXXXXXXXXXXXXXXXXOOOOOOOOOO....    ",
    "    ....oo..........XXXXXXXXXXXXXXXXXXOOOOOOOOOOOOOOXXXX....    ",
    "    ....oo..........XXXXXXXXXXXXXXXXXXOOOOOOOOOOOOOOXXXX....    ",
    "      ................XXXXXXXXXXOOOOOOOOOOOOXXXXXXXXXX....      ",
    "      ................XXXXXXXXXXOOOOOOOOOOOOXXXXXXXXXX....      ",
    "      ..................OOOOOOOOOOOOOOXXXXXXXXXXXXXX......      ",
    "      ..................OOOOOOOOOOOOOOXXXXXXXXXXXXXX......      ",
    "      ............ooooooooooOOOOXXXXXXXXXXXXXXXX..........      ",
    "      ............ooooooooooOOOOXXXXXXXXXXXXXXXX..........      ",
    "        ......oooooooooo........XXXXXXXXXXXX............        ",
    "        ......oooooooooo........XXXXXXXXXXXX............        ",
    "        ....oooooo................................oo....        ",
    "        ....oooooo................................oo....        ",
    "          ................................oooooooo....          ",
    "          ................................oooooooo....          ",
    "            ......................oooooooooooo......            ",
    "            ......................oooooooooooo......            ",
    "              ............oooooooooooooo..........              ",
    "              ............oooooooooooooo..........              ",
    "                ......oooooooooo................                ",
    "                ......oooooooooo................                ",
    "                    ........................                    ",
    "                    ........................                    ",
    "                          ............                          ",
    "                          ............                          ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                                "};

static xpm_row_t mercury[] = {
    /* columns rows colors chars-per-pixel */
    "64 64 6 1 ",
    "  c none",
    ". c #BD4D33",
    "X c #AD6843",
    "o c #CE6F52",
    "O c #BF8761",
    "+ c #D9B5A1",
    /* pixels */
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                          OOOOOOOOOOOO                          ",
    "                          OOOOOOOOOOOO                          ",
    "                    OOOOOOOO++++++++++OOOOOO                    ",
    "                    OOOOOOOO++++++++++OOOOOO                    ",
    "                OOOOOOOO++++++++++++++++++++OOOO                ",
    "                OOOOOOOO++++++++++++++++++++OOOO                ",
    "              XXXXOOOO++++++++++++++++++OOOOOOOOOO              ",
    "              XXXXOOOO++++++++++++++++++OOOOOOOOOO              ",
    "            XXXXXXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOO++OO            ",
    "            XXXXXXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOO++OO            ",
    "          OOOOXXXXOOOOOOOOOOOOOOOOOOOOOOOO++++++++++OO          ",
    "          OOOOXXXXOOOOOOOOOOOOOOOOOOOOOOOO++++++++++OO          ",
    "        OOOOOOOOOO++++++++++++++++++++++++++++++++++++oo        ",
    "        OOOOOOOOOO++++++++++++++++++++++++++++++++++++oo        ",
    "        ..OOOOOO++++++++++++++++++++++++++++++++++oooooo        ",
    "        ..OOOOOO++++++++++++++++++++++++++++++++++oooooo        ",
    "      ........OO++++++++++++++++++++++++++++oooooooooooooo      ",
    "      ........OO++++++++++++++++++++++++++++oooooooooooooo      ",
    "      ..........oooooooooooooooooooooooooooooooooooooooooo      ",
    "      ..........oooooooooooooooooooooooooooooooooooooooooo      ",
    "      ..........oooooooooooooooooooooooooooooooooooooooooo      ",
    "      ..........oooooooooooooooooooooooooooooooooooooooooo      ",
    "    OOOO........oooooooooooooooooooooooooooooooooooooo++++oo    ",
    "    OOOO........oooooooooooooooooooooooooooooooooooooo++++oo    ",
    "    OOOOOOOO....oooooooooooooooooooooooooooooooo++++++++++oo    ",
    "    OOOOOOOO....oooooooooooooooooooooooooooooooo++++++++++oo    ",
    "    OOOOOOOOOOOO++++++++++++++++++++++++++++++++++++++++++oo    ",
    "    OOOOOOOOOOOO++++++++++++++++++++++++++++++++++++++++++oo    ",
    "    ....OOOOOOOOOO++++++++++++++++++++++++++++++++++++++oooo    ",
    "    ....OOOOOOOOOO++++++++++++++++++++++++++++++++++++++oooo    ",
    "    ..........OOOO++++++++++++++++++++++++++++++oooooooooooo    ",
    "    ..........OOOO++++++++++++++++++++++++++++++oooooooooooo    ",
    "    oooo............oooooooooooooooooooooooooooooooooooooooo    ",
    "    oooo............oooooooooooooooooooooooooooooooooooooooo    ",
    "      oooooooo........oooooooooooooooooooooooooo++++++oooo      ",
    "      oooooooo........oooooooooooooooooooooooooo++++++oooo      ",
    "      oooooooooooooooooo++++++++++++++++++++++++++++oooooo      ",
    "      oooooooooooooooooo++++++++++++++++++++++++++++oooooo      ",
    "      XXXXXXoooooooooooooooo++++++++++++++++++++oooooooooo      ",
    "      XXXXXXoooooooooooooooo++++++++++++++++++++oooooooooo      ",
    "        XXXXXXXXXXoooooooooooooo++++++++++++ooooooXXXXXX        ",
    "        XXXXXXXXXXoooooooooooooo++++++++++++ooooooXXXXXX        ",
    "        OOXXXXXXXXXXXXXXooooooooooooooooooooXXXXXXXXXXXX        ",
    "        OOXXXXXXXXXXXXXXooooooooooooooooooooXXXXXXXXXXXX        ",
    "          OOOOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOOOO          ",
    "          OOOOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOOOO          ",
    "            OOOOOOOOOOXXXXXXXXXXXXXXXXXXXXXXXXOOOOOO            ",
    "            OOOOOOOOOOXXXXXXXXXXXXXXXXXXXXXXXXOOOOOO            ",
    "              OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO              ",
    "              OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO              ",
    "                XXXXXXOOOOOOOOOOOOOOOOOOOOXXXXXX                ",
    "                XXXXXXOOOOOOOOOOOOOOOOOOOOXXXXXX                ",
    "                    XXXXXXXXXXXXXXXXXXXXXXXX                    ",
    "                    XXXXXXXXXXXXXXXXXXXXXXXX                    ",
    "                          XXXXXXXXXXXX                          ",
    "                          XXXXXXXXXXXX                          ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                                "};
static xpm_row_t rock[] = {
    /* columns rows colors chars-per-pixel */
    "64 64 3 1 ",
    "  c none",
    ". c #4F362F",
    "X c #785247",
    /* pixels */
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                          ............                          ",
    "                          ............                          ",
    "                    ......XXXXXXXXXXXX......                    ",
    "                    ......XXXXXXXXXXXX......                    ",
    "                ......XXXXXX..XX......XXXXXX....                ",
    "                ......XXXXXX..XX......XXXXXX....                ",
    "              ....XXXXXX..XXXX........XX....XXXX..              ",
    "              ....XXXXXX..XXXX........XX....XXXX..              ",
    "            ....XX..XX..XX..XXXXXXXXXX....XXXXXXXX..            ",
    "            ....XX..XX..XX..XXXXXXXXXX....XXXXXXXX..            ",
    "          ....XX..XX..XX......XXXXXXXXXXXX....XX..XX..          ",
    "          ....XX..XX..XX......XXXXXXXXXXXX....XX..XX..          ",
    "        ......XXXX....XXXXXXXXXXXX....XX........XXXXXX..        ",
    "        ......XXXX....XXXXXXXXXXXX....XX........XXXXXX..        ",
    "        ....XXXX..XX....XXXX..XX........XXXX........XX..        ",
    "        ....XXXX..XX....XXXX..XX........XXXX........XX..        ",
    "      ......XX....XX....XX....XXXX....XXXXXXXXXX......XX..      ",
    "      ......XX....XX....XX....XXXX....XXXXXXXXXX......XX..      ",
    "      ....XX..XX....XXXX..XX..XX..XX....XX..XXXXXXXX..XX..      ",
    "      ....XX..XX....XXXX..XX..XX..XX....XX..XXXXXXXX..XX..      ",
    "      ....XXXX........XX..XXXXXXXX........XX..XX..XXXXXX..      ",
    "      ....XXXX........XX..XXXXXXXX........XX..XX..XXXXXX..      ",
    "    ......XX....XX..XX..XXXXXXXX..XX....XXXXXX..XXXX..XX....    ",
    "    ......XX....XX..XX..XXXXXXXX..XX....XXXXXX..XXXX..XX....    ",
    "    ..............XXXX....XXXX..XXXXXX..XXXX....XX..........    ",
    "    ..............XXXX....XXXX..XXXXXX..XXXX....XX..........    ",
    "    ....XX....XX....XX......XX..XX....XXXX..XX..XXXX..XX....    ",
    "    ....XX....XX....XX......XX..XX....XXXX..XX..XXXX..XX....    ",
    "    ............XX......XXXXXXXXXX......XXXXXXXX..XXXXXX....    ",
    "    ............XX......XXXXXXXXXX......XXXXXXXX..XXXXXX....    ",
    "    ....XX..XX......XX..XXXX..XX......XX..XX..XXXX....XX....    ",
    "    ....XX..XX......XX..XXXX..XX......XX..XX..XXXX....XX....    ",
    "    ..........XX......XXXX..XX......XX..XXXXXX..XX..XXXX....    ",
    "    ..........XX......XXXX..XX......XX..XXXXXX..XX..XXXX....    ",
    "      ..........XX..XXXX..XXXXXX....XXXXXX..XXXXXXXXXX....      ",
    "      ..........XX..XXXX..XXXXXX....XXXXXX..XXXXXXXXXX....      ",
    "      ....XX..XX............XXXXXX......XXXX....XX..XX....      ",
    "      ....XX..XX............XXXXXX......XXXX....XX..XX....      ",
    "      ..............XX..XX....XXXXXX......XXXX....XX......      ",
    "      ..............XX..XX....XXXXXX......XXXX....XX......      ",
    "        ....XX........XX....XXXX..XXXXXX..XX....XX......        ",
    "        ....XX........XX....XXXX..XXXXXX..XX....XX......        ",
    "        ........XX........XX....XX..XX..XX..............        ",
    "        ........XX........XX....XX..XX..XX..............        ",
    "          ........XX..XX..............XX....XX..XX....          ",
    "          ........XX..XX..............XX....XX..XX....          ",
    "            ................XX....XXXX..XX..........            ",
    "            ................XX....XXXX..XX..........            ",
    "              ..........XX..................XX....              ",
    "              ..........XX..................XX....              ",
    "                ................XX..XX..........                ",
    "                ................XX..XX..........                ",
    "                    ........................                    ",
    "                    ........................                    ",
    "                          ............                          ",
    "                          ............                          ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                                "};

static xpm_row_t sand[] = {
    /* columns rows colors chars-per-pixel */
    "64 64 3 1 ",
    "  c none",
    ". c #BFAC6B",
    "X c #C8B580",
    /* pixels */
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                          ............                          ",
    "                          ............                          ",
    "                    ........................                    ",
    "                    ........................                    ",
    "                ................XXXXXXXXXXXXXX..                ",
    "                ................XXXXXXXXXXXXXX..                ",
    "              ............XXXXXXXXXXXXXXXX........              ",
    "              ............XXXXXXXXXXXXXXXX........              ",
    "            ..........XXXXXXXXXXXXXXXX..............            ",
    "            ..........XXXXXXXXXXXXXXXX..............            ",
    "          ..........XXXXXXXXXXXXXXXX..................          ",
    "          ..........XXXXXXXXXXXXXXXX..................          ",
    "        ..........XXXXXXXXXXXXXXXXXXXXXX................        ",
    "        ..........XXXXXXXXXXXXXXXXXXXXXX................        ",
    "        ........XXXXXXXXXXXXXXXXXXXXXXXXXXXX............        ",
    "        ........XXXXXXXXXXXXXXXXXXXXXXXXXXXX............        ",
    "      ..........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....XX..      ",
    "      ..........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....XX..      ",
    "      ........XXXXXXXXXXXXXXXXXXXX....................XX..      ",
    "      ........XXXXXXXXXXXXXXXXXXXX....................XX..      ",
    "      ........XXXX..XXXXXXXX..XXXXXX................XXXX..      ",
    "      ........XXXX..XXXXXXXX..XXXXXX................XXXX..      ",
    "    ..........XX....XXXXXXXX....XXXXXXXX............XXXXXX..    ",
    "    ..........XX....XXXXXXXX....XXXXXXXX............XXXXXX..    ",
    "    ..........XX....XXXXXXXX......XXXXXXXXXX........XXXXXX..    ",
    "    ..........XX....XXXXXXXX......XXXXXXXXXX........XXXXXX..    ",
    "    ..........XX......XXXXXX......................XXXXXXXX..    ",
    "    ..........XX......XXXXXX......................XXXXXXXX..    ",
    "    ..........XX......XXXXXXXX....................XXXXXXXX..    ",
    "    ..........XX......XXXXXXXX....................XXXXXXXX..    ",
    "    ....................XXXXXXXX................XXXXXXXX....    ",
    "    ....................XXXXXXXX................XXXXXXXX....    ",
    "    ........................XXXXXXXX..........XXXXXXXX......    ",
    "    ........................XXXXXXXX..........XXXXXXXX......    ",
    "      ............XXXX..........XXXXXXXX....XXXXXX........      ",
    "      ............XXXX..........XXXXXXXX....XXXXXX........      ",
    "      ..............XXXX..................XXXX......XXXX..      ",
    "      ..............XXXX..................XXXX......XXXX..      ",
    "      ................XXXXXX......................XXXX....      ",
    "      ................XXXXXX......................XXXX....      ",
    "        ..................XXXXXX..............XXXXXX....        ",
    "        ..................XXXXXX..............XXXXXX....        ",
    "        ....................................XXXXXX......        ",
    "        ....................................XXXXXX......        ",
    "          ..............................XXXXXX........          ",
    "          ..............................XXXXXX........          ",
    "            ........................................            ",
    "            ........................................            ",
    "              ....................................              ",
    "              ....................................              ",
    "                ................................                ",
    "                ................................                ",
    "                    ........................                    ",
    "                    ........................                    ",
    "                          ............                          ",
    "                          ............                          ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                                "};

static xpm_row_t snow[] = {
    /* columns rows colors chars-per-pixel */
    "64 64 3 1 ",
    "  c none",
    ". c #95AFF7",
    "X c #BDCFFB",
    /* pixels */
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                          ............                          ",
    "                          ............                          ",
    "                    ........XXXXXXXXXX......                    ",
    "                    ........XXXXXXXXXX......                    ",
    "                ........XXXXXXXXXXXXXXXXXXXX....                ",
    "                ........XXXXXXXXXXXXXXXXXXXX....                ",
    "              ........XXXXXXXXXXXXXXXXXXXXXXXXXX..              ",
    "              ........XXXXXXXXXXXXXXXXXXXXXXXXXX..              ",
    "            ........XXXXXXXXXXXX......XXXXXXXXXXXX..            ",
    "            ........XXXXXXXXXXXX......XXXXXXXXXXXX..            ",
    "          ........XXXXXXXXXXXXXXXX........XXXXXXXXXX..          ",
    "          ........XXXXXXXXXXXXXXXX........XXXXXXXXXX..          ",
    "        ..........XXXXXXXX....XXXXXX........XXXXXXXXXX..        ",
    "        ..........XXXXXXXX....XXXXXX........XXXXXXXXXX..        ",
    "        ..........XXXXXXXX........XXXXXX........XXXXXX..        ",
    "        ..........XXXXXXXX........XXXXXX........XXXXXX..        ",
    "      ..............XXXXXXXX..........XXXX........XXXXXX..      ",
    "      ..............XXXXXXXX..........XXXX........XXXXXX..      ",
    "      ................XXXXXXXX..........XXXX........XXXX..      ",
    "      ................XXXXXXXX..........XXXX........XXXX..      ",
    "      ..................XXXXXXXX..........XXXX........XX..      ",
    "      ..................XXXXXXXX..........XXXX........XX..      ",
    "    ............XX..........XXXXXX..........XXXX......XXXX..    ",
    "    ............XX..........XXXXXX..........XXXX......XXXX..    ",
    "    ............XXXX..........XXXXXX..........XX........XX..    ",
    "    ............XXXX..........XXXXXX..........XX........XX..    ",
    "    ..............XXXX............XXXX..........XX......XX..    ",
    "    ..............XXXX............XXXX..........XX......XX..    ",
    "    ..............XXXXXX............XXXX........XX..........    ",
    "    ..............XXXXXX............XXXX........XX..........    ",
    "    ................XXXXXX............XXXX..................    ",
    "    ................XXXXXX............XXXX..................    ",
    "    ..................XXXXXX............XX..................    ",
    "    ..................XXXXXX............XX..................    ",
    "      ..................XXXXXX......................XXXX..      ",
    "      ..................XXXXXX......................XXXX..      ",
    "      ....................XXXXXXXX................XXXX....      ",
    "      ....................XXXXXXXX................XXXX....      ",
    "      ......................XXXXXXXXXX........XXXXXX......      ",
    "      ......................XXXXXXXXXX........XXXXXX......      ",
    "        ......................XXXXXXXXXXXXXXXXXXXX......        ",
    "        ......................XXXXXXXXXXXXXXXXXXXX......        ",
    "        ..........................XXXXXXXXXXXXXX........        ",
    "        ..........................XXXXXXXXXXXXXX........        ",
    "          ............................XXXXXXXX........          ",
    "          ............................XXXXXXXX........          ",
    "            ........................................            ",
    "            ........................................            ",
    "              ....................................              ",
    "              ....................................              ",
    "                ................................                ",
    "                ................................                ",
    "                    ........................                    ",
    "                    ........................                    ",
    "                          ............                          ",
    "                          ............                          ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                                "};

static xpm_row_t terran[] = {
    /* columns rows colors chars-per-pixel */
    "64 64 5 1 ",
    "  c none",
    ". c #29AF47",
    "X c #43D364",
    "o c #4839FD",
    "O c #786DFE",
    /* pixels */
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                          ......oooooo                          ",
    "                          ......oooooo                          ",
    "                    ........XXXXOOOOOO......                    ",
    "                    ........XXXXOOOOOO......                    ",
    "                ........XXXXXXOOOOOOOOOOXXXX....                ",
    "                ........XXXXXXOOOOOOOOOOXXXX....                ",
    "              ........XXXXXXXXOOOOOOOOOOXXXXXXXX..              ",
    "              ........XXXXXXXXOOOOOOOOOOXXXXXXXX..              ",
    "            ........XXXXXXXXOOOOOOOOOOOOOOXXXXXXXX..            ",
    "            ........XXXXXXXXOOOOOOOOOOOOOOXXXXXXXX..            ",
    "          ........XXXXXXXXOOOOOOOOOOOOOOOOXXXXXXXXXX..          ",
    "          ........XXXXXXXXOOOOOOOOOOOOOOOOXXXXXXXXXX..          ",
    "        ..........XXXXXXOOOOOOOOOOOOOOOOOOXXXXXXXXXXXX..        ",
    "        ..........XXXXXXOOOOOOOOOOOOOOOOOOXXXXXXXXXXXX..        ",
    "        ........XXXXXXOOOOOOOOOOOOOOOOOOOOXXXXXXXXXXXX..        ",
    "        ........XXXXXXOOOOOOOOOOOOOOOOOOOOXXXXXXXXXXXX..        ",
    "      ..........XXXXOOOOOOOOOOOOOOOOOOOOOOOOXXXXXXXXXXXX..      ",
    "      ..........XXXXOOOOOOOOOOOOOOOOOOOOOOOOXXXXXXXXXXXX..      ",
    "      ..........XXOOOOOOOOOOOOOOOOOOOOOOOOOOXXXXXXXXXXXX..      ",
    "      ..........XXOOOOOOOOOOOOOOOOOOOOOOOOOOXXXXXXXXXXXX..      ",
    "      ......ooooOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXXXXXXXXXXX..      ",
    "      ......ooooOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXXXXXXXXXXX..      ",
    "    ....ooooooooOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXXXXXXXXXXXXX..    ",
    "    ....ooooooooOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXXXXXXXXXXXXX..    ",
    "    ooooooooooooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXXXXXXXXXXX..    ",
    "    ooooooooooooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXXXXXXXXXXX..    ",
    "    ooooooooooooooOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXXXXXXXXXXX..    ",
    "    ooooooooooooooOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXXXXXXXXXXX..    ",
    "    ooooooooooooooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXXXXXXXXX..    ",
    "    ooooooooooooooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXXXXXXXXX..    ",
    "    ooooooooooooooooOOOOOOOOOOOOOOXXXXXXOOOOOOOOOOXXXXXX....    ",
    "    ooooooooooooooooOOOOOOOOOOOOOOXXXXXXOOOOOOOOOOXXXXXX....    ",
    "    ooooooooooooooooOOOOOOOOOOOOXXXXXXXXXXOOOOOOOOOOXXXX....    ",
    "    ooooooooooooooooOOOOOOOOOOOOXXXXXXXXXXOOOOOOOOOOXXXX....    ",
    "      ooooooooooooooooOOOOOOOOOOXXXXXXXXXXXXOOOOOOOOOO....      ",
    "      ooooooooooooooooOOOOOOOOOOXXXXXXXXXXXXOOOOOOOOOO....      ",
    "      oooo..ooooooooooooOOOOOOOOOOXXXXXXXXXXOOOOOOOOoooooo      ",
    "      oooo..ooooooooooooOOOOOOOOOOXXXXXXXXXXOOOOOOOOoooooo      ",
    "      oo......ooooooooooooooOOOOOOOOXXXXXXXXXXOOoooooooooo      ",
    "      oo......ooooooooooooooOOOOOOOOXXXXXXXXXXOOoooooooooo      ",
    "        ........ooooooooooooooooOOOOXXXXXXXX..oooooooooo        ",
    "        ........ooooooooooooooooOOOOXXXXXXXX..oooooooooo        ",
    "        ..........oooooooooooooooooo............oooooooo        ",
    "        ..........oooooooooooooooooo............oooooooo        ",
    "          ............oooooooooooooo............oooooo          ",
    "          ............oooooooooooooo............oooooo          ",
    "            ..............oooooooooooo........oooooo            ",
    "            ..............oooooooooooo........oooooo            ",
    "              ..............oooooooooooooooooooooo              ",
    "              ..............oooooooooooooooooooooo              ",
    "                ..............oooooooooooooooooo                ",
    "                ..............oooooooooooooooooo                ",
    "                    ............oooooooooooo                    ",
    "                    ............oooooooooooo                    ",
    "                          ........oooo                          ",
    "                          ........oooo                          ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                                "};

static xpm_row_t toxic[] = {
    /* columns rows colors chars-per-pixel */
    "64 64 6 1 ",
    "  c none",
    ". c #831D52",
    "X c #AD256C",
    "o c #E08305",
    "O c #DE0EEF",
    "+ c #F5C187",
    /* pixels */
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                          XXXXXXXXXXXX                          ",
    "                          XXXXXXXXXXXX                          ",
    "                    XXXXXXXXOOOOOOOOOOXXXXXX                    ",
    "                    XXXXXXXXOOOOOOOOOOXXXXXX                    ",
    "                XXXXXXXXOOOOOOOOOOOOOOOOOOXXXXXX                ",
    "                XXXXXXXXOOOOOOOOOOOOOOOOOOXXXXXX                ",
    "              XXXXXXXXOOOOOOOOOOOOOOOOOOXXXXXXXXXX              ",
    "              XXXXXXXXOOOOOOOOOOOOOOOOOOXXXXXXXXXX              ",
    "            XXXXXXXXOOOOOOOOOOOOOOOOOOXXXXXXXXOOOOXX            ",
    "            XXXXXXXXOOOOOOOOOOOOOOOOOOXXXXXXXXOOOOXX            ",
    "          XXXXooXXOOOOOOOOOOOOOOOOXXXXXXXXOOOOOOOOOOXX          ",
    "          XXXXooXXOOOOOOOOOOOOOOOOXXXXXXXXOOOOOOOOOOXX          ",
    "        XXXXoooooo++OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXXXXX        ",
    "        XXXXoooooo++OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXXXXX        ",
    "        XXXXoooo++++++++OOOOOOOOOOOOOOOOOOOOOOOOOOXXXXXX        ",
    "        XXXXoooo++++++++OOOOOOOOOOOOOOOOOOOOOOOOOOXXXXXX        ",
    "      ....XXXXoooo++++++++++OOOOOOOOOOOOOOXXOOOOOOXXXX++OO      ",
    "      ....XXXXoooo++++++++++OOOOOOOOOOOOOOXXOOOOOOXXXX++OO      ",
    "      ......XXXXoooooo++++++++++++++XXXXXXOOOOOOXXXX++++OO      ",
    "      ......XXXXoooooo++++++++++++++XXXXXXOOOOOOXXXX++++OO      ",
    "      XX......XXXXooooooooooooooooXXXXXXOOOOOOOOXXXX++++OO      ",
    "      XX......XXXXooooooooooooooooXXXXXXOOOOOOOOXXXX++++OO      ",
    "    ooXXXXXX....XXXXXXooooooooOOOOOOOOOOOOOOOOXXXX++++++ooXX    ",
    "    ooXXXXXX....XXXXXXooooooooOOOOOOOOOOOOOOOOXXXX++++++ooXX    ",
    "    ooooXXXXXXXXXXXXXXXXXXOOOOOOOOOOOOOOOOOOXXXX++++++ooXXXX    ",
    "    ooooXXXXXXXXXXXXXXXXXXOOOOOOOOOOOOOOOOOOXXXX++++++ooXXXX    ",
    "    XXooooooXXXXXXOOXXXXXXXXXXXXXXXXXXXXXXXXXXXX++++ooooOOXX    ",
    "    XXooooooXXXXXXOOXXXXXXXXXXXXXXXXXXXXXXXXXXXX++++ooooOOXX    ",
    "    ....XXooooXXXXOOOOOOOOXXXXXXXXXXXXXXXXXXXX++++ooooOOOOXX    ",
    "    ....XXooooXXXXOOOOOOOOXXXXXXXXXXXXXXXXXXXX++++ooooOOOOXX    ",
    "    ........XXXXXXXXOOOOOOOOOOOOOOXXXXXXXXXX++ooooooOOOOXXXX    ",
    "    ........XXXXXXXXOOOOOOOOOOOOOOXXXXXXXXXX++ooooooOOOOXXXX    ",
    "    XXXX........XXXXOOOOOOOOOOXXXXXXXXXX++ooooooXXOOOOOOXXXX    ",
    "    XXXX........XXXXOOOOOOOOOOXXXXXXXXXX++ooooooXXOOOOOOXXXX    ",
    "      XXXXXX..........XXXXXXXXXXXXXXXXooooooXXXXOOOOOOXXXX      ",
    "      XXXXXX..........XXXXXXXXXXXXXXXXooooooXXXXOOOOOOXXXX      ",
    "      XXXXXXXXXX........XXXXXXXXXXXXXXXXXXXXOOOOOOOOXXXXXX      ",
    "      XXXXXXXXXX........XXXXXXXXXXXXXXXXXXXXOOOOOOOOXXXXXX      ",
    "      XXXXXXXXXXXXXXXXXXXXXXOOOOOOOOOOOOOOOOOOOOXXXXXXXXXX      ",
    "      XXXXXXXXXXXXXXXXXXXXXXOOOOOOOOOOOOOOOOOOOOXXXXXXXXXX      ",
    "        ..XXXXXXXXXXXXXXXXXXXXXXOOOOOOOOOOOOXXXXXXXX....        ",
    "        ..XXXXXXXXXXXXXXXXXXXXXXOOOOOOOOOOOOXXXXXXXX....        ",
    "        ....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..........        ",
    "        ....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..........        ",
    "          ....ooooooooXXXXXXXXXXXXXXXXXXXX..........XX          ",
    "          ....ooooooooXXXXXXXXXXXXXXXXXXXX..........XX          ",
    "            ....ooooooooooXXXXXXXXXXXXXXXXXXXXXXXXXX            ",
    "            ....ooooooooooXXXXXXXXXXXXXXXXXXXXXXXXXX            ",
    "              ......ooooooooooooooooooooooXXXXXXXX              ",
    "              ......ooooooooooooooooooooooXXXXXXXX              ",
    "                ..........ooooooooooXXXXXXXXXXXX                ",
    "                ..........ooooooooooXXXXXXXXXXXX                ",
    "                    ........................                    ",
    "                    ........................                    ",
    "                          ............                          ",
    "                          ............                          ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                                "};
